from .models import RiskRecord

RISK_RECORDS: list[RiskRecord] = [
    RiskRecord(
        id="BR-07",
        name="Bridge BR-07",
        asset_type="Bridge",
        latitude=20.2961,
        longitude=85.8245,
        risk_score=0.91,
        risk_level="CRITICAL",
        priority_score=0.95,
        rainfall_24h_mm=182,
        elevation_m=12,
        water_distance_km=0.35,
        exposure=0.92,
        recommended_action="Priority inspection before the next response cycle.",
    ),
    RiskRecord(
        id="RD-14",
        name="Road Segment RD-14",
        asset_type="Road",
        latitude=20.4625,
        longitude=85.8830,
        risk_score=0.82,
        risk_level="HIGH",
        priority_score=0.86,
        rainfall_24h_mm=145,
        elevation_m=19,
        water_distance_km=0.62,
        exposure=0.79,
        recommended_action="Inspect within the next 6 hours.",
    ),
    RiskRecord(
        id="WF-03",
        name="Water Facility WF-03",
        asset_type="Water Facility",
        latitude=20.2710,
        longitude=86.6930,
        risk_score=0.76,
        risk_level="HIGH",
        priority_score=0.79,
        rainfall_24h_mm=121,
        elevation_m=24,
        water_distance_km=0.85,
        exposure=0.74,
        recommended_action="Monitor closely and prepare inspection resources.",
    ),
    RiskRecord(
        id="A-02",
        name="Infrastructure Asset A-02",
        asset_type="Infrastructure",
        latitude=20.2600,
        longitude=85.8200,
        risk_score=0.43,
        risk_level="MODERATE",
        priority_score=0.44,
        rainfall_24h_mm=82,
        elevation_m=38,
        water_distance_km=1.40,
        exposure=0.55,
        recommended_action="Continue monitoring under the selected scenario.",
    ),
    RiskRecord(
        id="M-01",
        name="Monitoring Zone M-01",
        asset_type="Monitoring",
        latitude=20.4900,
        longitude=85.6200,
        risk_score=0.19,
        risk_level="LOW",
        priority_score=0.20,
        rainfall_24h_mm=41,
        elevation_m=64,
        water_distance_km=3.10,
        exposure=0.28,
        recommended_action="Routine monitoring.",
    ),
]
